# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo:7.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: movietracker_dbAdmin
      MONGO_INITDB_ROOT_PASSWORD: CDE7Yn2C.q!a7-x
    ports:
      - "27017:27017"